### ISSUE TITLE
Why need ReactDOM ?

### ISSUE THREAD

**Issue by nish1013** [fedosejev/react-essentials#10]
Hi ,

What is the requirement of having ReactDOM , can't we just use React.render ?

var React = require('react');
var ReactDOM = require('react-dom');
var reactElement = React.createElement('h1');
ReactDOM.render(reactElement, document.getElementById('react-application'));

**Comment by fedosejev** [comment]
@nish1013 check https://facebook.github.io/react/blog/2015/07/03/react-v0.14-beta-1.html#two-packages
