### ISSUE TITLE
Unexpected token issue

### ISSUE THREAD

**Issue by tajoarl** [fedosejev/react-essentials#100]
## An error occurred after npm start.

node version : v6.9.2
npm version : 3.10.9
=====================================================================

> snapkite-engine@0.1.2 start ../React-workspace/twStreamingEX/snapkite-engine
> node app.js

module.js:590
    throw err;
    ^

SyntaxError: ../React-workspace/twStreamingEX/snapkite-engine/config.json: Unexpected token “ in JSON at position 191
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:587:27)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (../React-workspace/twStreamingEX/snapkite-engine/app.js:1:85)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snapkite-engine@0.1.2 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the snapkite-engine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs snapkite-engine
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls snapkite-engine
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ../React-workspace/twStreamingEX/snapkite-engine/npm-debug.log

**Comment by fedosejev** [comment]
@tajoarl instead of `“` use `"`.
