### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by zxy7** [fedosejev/react-essentials#101]
E:\a\snapterest\snapkite-engine>npm start

> snapkite-engine@0.1.2 start E:\a\snapterest\snapkite-engine
> node app.js

E:\a\snapterest\snapkite-engine\node_modules\node-tweet-stream\lib\twitter.js:28

    throw new Error('Oauth credentials required')
    ^

Error: Oauth credentials required
    at new Twitter (E:\a\snapterest\snapkite-engine\node_modules\node-tweet-stre
am\lib\twitter.js:28:11)
    at module.exports (E:\a\snapterest\snapkite-engine\controllers\twitter.js:85
:17)
    at Object.<anonymous> (E:\a\snapterest\snapkite-engine\app.js:11:33)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "E:\\MyDownloads\\Download\\node.exe" "E:\\MyDownloads\\Download\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snapkite-engine@0.1.2 start script 'node app.js'.
npm ERR! This is most likely a problem with the snapkite-engine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs snapkite-engine
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls snapkite-engine
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\a\snapterest\snapkite-engine\npm-debug.log

**Comment by zxy7** [comment]
solved
remember to set up key  in ~/snapkite-engine/config.json

**Comment by fedosejev** [comment]
Yeah, please check the docs: https://github.com/Snapkite/snapkite-engine#install
