### ISSUE TITLE
error starting npm 

### ISSUE THREAD

**Issue by motomaniak** [fedosejev/react-essentials#106]
After installing everything and setting the filters when I try npm start in snapkite-engines folder I am getting an error. Attached is a screen shot of the log since it won't let me attach it and a screen shot of the terminal. 
![screenshot from 2017-02-06 10-43-38](https://cloud.githubusercontent.com/assets/23463564/22661164/37ba072e-ec59-11e6-8388-c38d72bc8e87.png)

![screenshot from 2017-02-06 10-37-55](https://cloud.githubusercontent.com/assets/23463564/22661124/0b7c3218-ec59-11e6-9224-c7ad4832dca2.png)

**Comment by natty4GitHub** [comment]
I have similar error. I finished adding the filters to the config.json and did an npm start and found the following error. Please let me know if anyone knows where is went wrong ?
![screen shot 2017-02-16 at 7 44 00 pm](https://cloud.githubusercontent.com/assets/9864568/23047930/cb2eb14c-f480-11e6-951e-fd65a5946810.png)

**Comment by natty4GitHub** [comment]
Couldn't get it to work even after upgrading npm version.
![screen shot 2017-02-16 at 7 54 39 pm] . 

(https://cloud.githubusercontent.com/assets/9864568/23048119/cf8d1eb2-f481-11e6-9bd0-7c69b906bfdb.png) .

**Comment by fedosejev** [comment]
@motomaniak looks like you have no `node` command available. 

What happens if you run `node -v` in Terminal? You might need to add path to where `node` is installed to your `$PATH` variable.

**Comment by fedosejev** [comment]
@natty4GitHub did you add your Twitter API keys to `config.json`? If yes, can you please upload a screenshot of an error message that you get when you run `npm start`.

**Comment by natty4GitHub** [comment]
@fedosejev Thank you for the quick response.in  my last two comments i uploaded two screenshots of the *npm start*  right before and after npm upgrade.

 Again i am pasting the screen shot of the following below in reverse chronology.

III. npm start screenshot. ( to show the error).
II. contents of config.json.(to ensure keys and filters)
I. config.json (to ensure the logical path).

![screen shot 2017-02-17 at 11 06 40 am](https://cloud.githubusercontent.com/assets/9864568/23072836/380dd3f8-f501-11e6-9c12-db6e6595f9c5.png)
Contents of config.json.
![screen shot 2017-02-17 at 11 04 45 am](https://cloud.githubusercontent.com/assets/9864568/23072779/f9b955a0-f500-11e6-9477-3e150618690b.png)
path of config.json 
![screen shot 2017-02-17 at 10 59 49 am](https://cloud.githubusercontent.com/assets/9864568/23072713/b7b166b6-f500-11e6-96bd-2236c93fde2c.png)

Please let me know where i am going wrong or what i am missing ?

**Comment by natty4GitHub** [comment]
@fedosejev  I found somehow, i missed the copy of config.json into those filters. 

However after the command  "npm start", i do not see any right after Listening on port 3000. Is this expected ?. I am afraid it's not up running...

From the book, i am not sure what to expect after the command npm start ?
 Please see attached screenshot right after.
![screen shot 2017-02-17 at 12 17 11 pm](https://cloud.githubusercontent.com/assets/9864568/23075604/25ba5f0a-f50b-11e6-8ae5-58cbd03a7c40.png)

Response much appreciated.

**Comment by fedosejev** [comment]
@natty4GitHub good catch!

Yes, everything works as expected now.

It looks like nothing is happening, but actually `snapchat-engine` receives and emits tweets. To see that you can add the following line in `snapkite-engine/app.js` file:

`console.log(tweet);`

Before this line: https://github.com/Snapkite/snapkite-engine/blob/master/app.js#L34

Then run `npm start` and you'll see tweets printed in Terminal.

**Comment by natty4GitHub** [comment]
Thank you very much .. It works .awesome.. please find the screenshot. Actually it took sometime for tweets to come through... 

![screen shot 2017-02-17 at 7 21 56 pm](https://cloud.githubusercontent.com/assets/9864568/23087976/6889229a-f546-11e6-9797-725a1281ceba.png)

**Comment by fedosejev** [comment]
@natty4GitHub that's awesome. I am glad to help!
