### ISSUE TITLE
The Snapterest demo site doesn't seem to work?

### ISSUE THREAD

**Issue by joyfulelement** [fedosejev/react-essentials#12]
Hi,

I was trying to preview the live demo of Snapterest by visiting the given website: 
http://fedosejev.github.io/react-essentials-project/
But it seems failed to load the backend data it needs with time out errors.

Any idea?

<img width="505" alt="2015-10-16 21_30_14-snapterest can t load" src="https://cloud.githubusercontent.com/assets/5963818/10556286/379685ae-744d-11e5-9524-862cb01139d6.png">

**Comment by fedosejev** [comment]
Hi @joyfulelement, thanks for pointing this out - it's up now!
