### ISSUE TITLE
Snapkite Engine NPM Start fails on OSX - NPM Log messages below

### ISSUE THREAD

**Issue by fontanajg** [fedosejev/react-essentials#13]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.4
3 info using node@v4.1.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart snapkite-engine@0.1.2
6 info start snapkite-engine@0.1.2
7 verbose unsafe-perm in lifecycle true
8 info snapkite-engine@0.1.2 Failed to exec start script
9 verbose stack Error: snapkite-engine@0.1.2 start: `node app.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid snapkite-engine@0.1.2
11 verbose cwd /Users/Joe/snapkite-engine
12 error Darwin 14.5.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.1.2
15 error npm  v2.14.4
16 error code ELIFECYCLE
17 error snapkite-engine@0.1.2 start: `node app.js`
17 error Exit status 1
18 error Failed at the snapkite-engine@0.1.2 start script 'node app.js'.
18 error This is most likely a problem with the snapkite-engine package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node app.js
18 error You can get their info via:
18 error     npm owner ls snapkite-engine
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by fedosejev** [comment]
@fontanajg try running `snapkite-engine` with `sudo`?

Navigate to `snapkite-engine` directory and run: `sudo npm start`

**Comment by fontanajg** [comment]
That worked.  Thank you.
