### ISSUE TITLE
getting error while starting npm (i am setting up envt to learn react and making a small project as mentioned in the book)

### ISSUE THREAD

**Issue by vaaishalijain** [fedosejev/react-essentials#130]
Here is the following error: 

SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\VINOD JAIN\snapkite-engine\node_modules\node-tweet-stream\node_modules\request\node_modules\hawk\lib\index.js:5:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the snapkite-engine@0.1.2 start script.
npm ERR! This is most likely a problem with the snapkite-engine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls snapkite-engine
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! cwd C:\Users\VINOD JAIN\snapkite-engine
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\VINOD JAIN\snapkite-engine\npm-debug.log
npm ERR! not ok code 0

**Comment by sonismile** [comment]
Same issue I am facing with the Snapkite engine while starting npm.Can somebody please help.

**Comment by replicants39715** [comment]
@vaaishalijain What node.js version do you have? In your terminal, type `node -v`. Seems like you might have to update it. The current version is 9.11.1. [https://nodejs.org/en/](url)

**Comment by SHUBHAMDAVE001** [comment]
First of all as u said @vaaishalijain u can uninstall the node and install the latest version.
may be it is the fault of node moulde.
here i am attaching a link for installation.
[https://reactjs.org/docs/add-react-to-a-new-app.html](url)
