### ISSUE TITLE
Should I run a server for index.html? URL?

### ISSUE THREAD

**Issue by askeydev** [fedosejev/react-essentials#18]
Sorry, I think I missed a step.  Everything installed successfully.  I have just installed React and React DOM and going though the updates to app.js.  Was I supposed to start a sever in order to view index.html?  I have the snapkite engine running on port 3011.  I assume I need to run a node server also.  What is the command to start the server?
I understand the code, but did not want to go too far if I am supposed to be running the examples.
This is the last code I added:
var section = React.createElement('section', { className: 'container'}, reactFragment); 

-Thanks

**Comment by phil-lauffenburger** [comment]
No, just open index.html in a browser.

**Comment by gerturo** [comment]
Snapkite Engine must be running, see page 9: open a terminal, and from within the snapkite-engine dir type `npm start`.

**Comment by fedosejev** [comment]
@lauffenp @gerturo :+1:
