### ISSUE TITLE
Snapkite: npm start throws error

### ISSUE THREAD

**Issue by brennanerbz** [fedosejev/react-essentials#2]
After Snapkite setup, fails to start app.js.

**Comment by fedosejev** [comment]
Hey @brennanerbz thanks for creating an issue. Could you please let me know what error message you get. Thanks!

**Comment by jodyb** [comment]
I'm also getting an error. Can't connect to MongoDB

[Snapkite][Socket] Listening on port 3000
[Snapkite][Database][Error] Make sure MongoDB is running

**Comment by cooldot** [comment]
Same error as jodyb...
[Snapkite][Socket] Listening on port 3000
[Snapkite][Database][Error] Make sure MongoDB is running

**Comment by kdenz** [comment]
Just open another terminal and type "mongod" without the brackets. Then it shall be fine.
![image](https://cloud.githubusercontent.com/assets/12795428/9699707/0568ef02-541f-11e5-9db5-10004a4191ca.png)

**Comment by davidmansy** [comment]
I have just started reading the book. I installed snapkite and I get the same error. What I did is to set the prop 'storeTweets' to false in the config.json of snapkite. Now when I start snapkite I don't get any error as it does not count on mongodb to run. If storing the tweets in a mongodb database is not needed for this demo app, then it should be ok.

**Comment by fedosejev** [comment]
@davidmansy good point. I've updated https://github.com/Snapkite/snapkite-engine so that now `storeTweets` is set to `false` by default.

**Comment by fedosejev** [comment]
@jodyb, @cooldot make sure you're running MongoDB. As @kdenz suggested: open a new Terminal window and type: `mongod` - if you have MongoDB installed. Otherwise, open `./snapkite-engine/config.json` file and change `"storeTweets": true,` to `"storeTweets": false,`.
