### ISSUE TITLE
can't start snapkite-engine

### ISSUE THREAD

**Issue by JeanOsorio** [fedosejev/react-essentials#20]
> snapkite-engine@0.1.2 start /Users/Jean/repos/react-essentials/snapkite-engine
> node app.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'socket.io'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/Users/Jean/repos/react-essentials/snapkite-engine/controllers/socket.js:5:15)
    at Object.<anonymous> (/Users/Jean/repos/react-essentials/snapkite-engine/app.js:4:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snapkite-engine@0.1.2 start script 'node app.js'.
npm ERR! This is most likely a problem with the snapkite-engine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls snapkite-engine
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Jean/repos/react-essentials/snapkite-engine/npm-debug.log

**Comment by eadbhard** [comment]
Hi, I have the same issue. I see you closed yours. Did you solved it? If so, how? Thanks!

**Comment by JeanOsorio** [comment]
I was using another version, so I install the same version of the book.

**Comment by eadbhard** [comment]
Hola Jean, gracias por responder. Estabas usando una vesion diferente de...? snap-kite, node, python...?

**Comment by JeanOsorio** [comment]
Hola, mira la verdad que estaba usando una versión distinta tanto de snap-kite como de node, el problema fue que tenía otro proyecto en una versión superior de node y por eso no me funcionaba, como no conseguí una solucion, decidí usar el node versión manager e instale las versiones que dice el libro. Cualquier cosa me ve avisas y te pasó mi código.

**Comment by eadbhard** [comment]
Muchas gracias. En mi caso era el proxy el problema y ya cerré mi issue comentando esto. Aún así estoy usando las versiones del libro como me recomendaste. Gracias de nuevo, un saludo.
