### ISSUE TITLE
Error running Chapter 4 code...

### ISSUE THREAD

**Issue by joetidee** [fedosejev/react-essentials#22]
I copied the code from Github to app.js and Application.react.js, then ran gulp, but received the following error - should I be able to run this code?

![gulp_error](https://cloud.githubusercontent.com/assets/8842431/11378053/4a3ef1fc-92e1-11e5-8a8d-de87d9c8f82d.jpg)

**Comment by joetidee** [comment]
After lots of searching, someone suggested installing a Babel preset:

`sudo npm install --save-dev babel-preset-react`

and then editing my gulp.js file transform to read:

```
gulp.task('default', function() {
    return  browserify('./source/app.js')
        .transform(babelify, {presets:["react"]})
        .bundle()
        .pipe(source('snapterest.js'))
        .pipe(gulp.dest('./build'));

});
```

how c ome this wasn't included in the book?

**Comment by fedosejev** [comment]
@joetidee most likely you're using the newer version of `babelify`. At the time of writing, the latest version  was `6.2.0`. Your `package.json` file should have the following `devDependencies`:

``` json
  "devDependencies": {
    "babelify": "^6.2.0",
    "browserify": "^11.0.1",
    "gulp": "^3.9.0",
    "vinyl-source-stream": "^1.1.0"
  },
```

Please check if that's the case.

**Comment by joetidee** [comment]
So babelify have retrograded their package to no longer parse JSX!? Here is my package.json file:

```
"devDependencies": {
    "babel-preset-react": "^6.1.18",
    "babelify": "^7.2.0",
    "browserify": "^12.0.1",
    "gulp": "^3.9.0",
    "vinyl-source-stream": "^1.1.0"
  },
```

**Comment by fedosejev** [comment]
@joetidee yes, please check https://github.com/babel/babelify - with the latest version of `babelify` you need to install `babel-preset-react` separately in order to parse JSX.
