### ISSUE TITLE
Error installing snapkite client...

### ISSUE THREAD

**Issue by joetidee** [fedosejev/react-essentials#25]
Tried installing it, got this error - help :(

![error](https://cloud.githubusercontent.com/assets/8842431/11428893/9a60e874-9468-11e5-8385-3cc020261ec0.jpg)

**Comment by fedosejev** [comment]
Hey @joetidee if you're on Ubuntu then run the following command: `sudo apt-get install build-essential`, and then try again.

**Comment by joetidee** [comment]
Tried this. Now getting "make: g++: Command not found" (?)

**Comment by joetidee** [comment]
ok, no got it.
