### ISSUE TITLE
JSX is not working

### ISSUE THREAD

**Issue by Taieb** [fedosejev/react-essentials#26]
Hello,

In the 2nd chapter I tried the example with JSX and the .transform(babelify) function call and I have an error when I run gulp 

events.js:85
      throw er; // Unhandled 'error' event
SyntaxError:

It begin at var listOfItems = **<**ul

I found the solution on issue #14

**Comment by eadbhard** [comment]
Hi there... I have exactly the same problem. I see you closed your issue. Would you please let us know what did you do to solve it? Thanks in advance and regards.
