### ISSUE TITLE
Unexpected token error upon running gulp command and using babelify with JSX

### ISSUE THREAD

**Issue by jtabone16** [fedosejev/react-essentials#40]
Here's the error I'm getting early on in the snapterest demo app:

`SyntaxError: /Users/johntabone/Documents/development/snapterest/source/app.js: Unexpected token`(3:18)
`var React = require('react');
`  var ReactDOM = require('react-dom');
`  var listOfItems = <ul className="list-of-items">

It's choking on the < character when declaring the listOfItems element. Any help would be appreciated!

**Comment by duanec** [comment]
I had the same issue. I believe the current version of babelify does not include the presets needed to parse the '<' as described here: https://github.com/babel/babelify. I did `npm install --save-dev babel-preset-react` and then modified the .transform line in gulpfile.js to `.transform(babelify, {presets: "react"})` and it parsed ok afterwards.

**Comment by fedosejev** [comment]
@duanec :+1:

**Comment by leonormes** [comment]
Thanks @duanec!

**Comment by duanec** [comment]
Welcome.

**Comment by jtabone16** [comment]
Thanks @duanec !

**Comment by giuleon** [comment]
@duanec 👍
