### ISSUE TITLE
First NPM Start

### ISSUE THREAD

**Issue by ghost** [fedosejev/react-essentials#42]
Sams-MacBook-Pro:snapkite-engine White$ npm start

> snapkite-engine@0.1.2 start /Users/White/DevBox/snapkite-engine
> node app.js

module.js:417
    throw err;
    ^

SyntaxError: /Users/White/DevBox/snapkite-engine/config.json: Unexpected token “
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:414:27)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/Users/White/DevBox/snapkite-engine/app.js:1:23)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snapkite-engine@0.1.2 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the snapkite-engine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls snapkite-engine
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/White/DevBox/snapkite-engine/npm-debug.log
[npm-debug.pdf](https://github.com/fedosejev/react-essentials/files/72659/npm-debug.pdf)

seems like theres an extra " in the config.json but I can't see one, I'll attach this and log, thank you in advance!

[config.pdf](https://github.com/fedosejev/react-essentials/files/72661/config.pdf)

**Comment by fedosejev** [comment]
@swhitedev notice that there is a different type of double quotes around `my`: `"trackKeywords": “my”`

Replace `“` with `"` and try again.

**Comment by ghost** [comment]
ahh so rookie! thanks for the rapid reply, however this has led me to another issue, I'm now getting 
Error: Cannot find module './config.json'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/Users/White/DevBox/snapkite-engine/filters/snapkite-filter-is-retweet/index.js:1:14)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snapkite-engine@0.1.2 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the snapkite-engine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls snapkite-engine
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/White/DevBox/snapkite-engine/npm-debug.log

which seems weird as it was just throwing an error from part of that file! I can see another user had this issue but closed it themselves without an update!

**Comment by fedosejev** [comment]
This time, it can't find `/Users/White/DevBox/snapkite-engine/filters/snapkite-filter-is-retweet/config.json` file. Make sure you've created it.

**Comment by ghost** [comment]
Sweet thanks! I had created it but it was in the wrong directory! thanks for the quick response!
