### ISSUE TITLE
First RUN npm start

### ISSUE THREAD

**Issue by alvieamar** [fedosejev/react-essentials#43]
> snapkite-engine@0.1.2 start /var/www/snapkite-engine
> node app.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1135:5)
    at module.exports (/var/www/snapkite-engine/controllers/socket.js:14:10)
    at Object.<anonymous> (/var/www/snapkite-engine/app.js:4:34)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

npm ERR! Linux 3.19.0-15-generic
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.25
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the snapkite-engine@0.1.2 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the snapkite-engine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs snapkite-engine
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls snapkite-engine
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/snapkite-engine/npm-debug.log

**Comment by fedosejev** [comment]
@alvieamar the port number is already taken. Try changing the port number.

**Comment by neonbrown82** [comment]
I encountered a different error, but in the exact same place:

> snapkite-engine@0.1.2 start /Users/Tyler/snapkite-engine
> node app.js

module.js:489
    throw err;
          ^
SyntaxError: /Users/Tyler/snapkite-engine/config.json: Unexpected token  
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:486:27)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Tyler/snapkite-engine/app.js:1:85)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snapkite-engine@0.1.2 start script 'node app.js'.
npm ERR! This is most likely a problem with the snapkite-engine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls snapkite-engine
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Tyler/snapkite-engine/npm-debug.log

**Comment by fedosejev** [comment]
@neonbrown82 how does your  `/Users/Tyler/snapkite-engine/config.json` file look like?

**Comment by neonbrown82** [comment]
I found the problem. When I copied and pasted my accessTokenSecret, evidently it had copied a hard return in between the opening quote and the first character. Tricky tricky. Thanks for being so prompt with the support, however. :)

**Comment by fedosejev** [comment]
@neonbrown82 welcome, thanks for getting the book!
