### ISSUE TITLE
NPM Error!!!

### ISSUE THREAD

**Issue by coryell1287** [fedosejev/react-essentials#44]
> snapkite-engine@0.1.2 start /var/lib/tomcat8/webapps/ROOT/Snapterest/snapkite-engine
> node app.js

[Snapkite][Socket] Listening on port 3000

module.js:340
    throw err;
    ^
Error: Cannot find module './config.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/lib/tomcat8/webapps/ROOT/Snapterest/snapkite-engine/filters/snapkite-filter-is-possibly-sensitive/index.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the snapkite-engine@0.1.2 start script.
npm ERR! This is most likely a problem with the snapkite-engine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls snapkite-engine
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.2.0-22-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /var/lib/tomcat8/webapps/ROOT/Snapterest/snapkite-engine
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/lib/tomcat8/webapps/ROOT/Snapterest/snapkite-engine/npm-debug.log
npm ERR! not ok code 0

**Comment by fedosejev** [comment]
@coryell1287 make sure you've created `/var/lib/tomcat8/webapps/ROOT/Snapterest/snapkite-engine/filters/snapkite-filter-is-possibly-sensitive/config.json` file.

**Comment by coryell1287** [comment]
Thanks. When I did the `cp example.json config.json` command, I didn't bother to check to see whether I had actually copied the file. I just assume that I did. I will be more careful next time.

**Comment by fedosejev** [comment]
@coryell1287 :+1:
