### ISSUE TITLE
Error running snapkite-engine

### ISSUE THREAD

**Issue by jaimesm** [fedosejev/react-essentials#59]
Hello,Artemij,  I get the below error when running snapkite-engine.  Any suggestions, please?
## Jaime

> node app.js

module.js:443
    throw err;
    ^

SyntaxError: /Users/jaimesuarez-murias/snapkite-engine/config.json: Unexpected token “
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:440:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Objec

**Comment by fedosejev** [comment]
Hi @jaimesm, looks like you have invalid double quote character in your `/Users/jaimesuarez-murias/snapkite-engine/config.json` file.

Try replacing this character `“` with that one `"`.

Let me know if that helps!

**Comment by jaimesm** [comment]
Thank you Artemij,  this is embarrassing!  I'm used to using Windows computers but now I'm using a Mac.  It was using the wrong double quote characters!!
Take care and thank you again.
Jaime
