### ISSUE TITLE
Error installing gulp

### ISSUE THREAD

**Issue by cqhuynh** [fedosejev/react-essentials#60]
Got following errors when run this command: nam install --global gulp
 Error: EACCES, mkdir '/usr/local/lib/node_modules/gulp'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/gulp']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/gulp',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/gulp',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'Object.oncomplete (fs.js:108:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 15.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "--global" "gulp"
npm ERR! cwd /Users/chrishuynh/snapterest
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! path /usr/local/lib/node_modules/gulp
npm ERR! fstream_path /usr/local/lib/node_modules/gulp
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/usr/local/lib/node_modules/gulp'
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/chrishuynh/snapterest/npm-debug.log
npm ERR! not ok code 0

**Comment by fedosejev** [comment]
Hey @cqhuynh, try running: `sudo npm install --global gulp`

**Comment by cqhuynh** [comment]
Thanks, it worked but now when I run gulp, I got this error:
Error: Cannot find module 'concat-map'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/chrishuynh/snapterest/node_modules/babelify/node_modules/babel-core/node_modules/minimatch/node_modules/brace-expansion/index.js:1:79)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Could you help me please?

Thanks
Chris
