### ISSUE TITLE
Chapter 1:"npm start" had many errors 

### ISSUE THREAD

**Issue by ghost** [fedosejev/react-essentials#87]
alyssadeMac-mini:snapkite-engine alyssa$ pwd
/Users/alyssa/snapkite-engine
alyssadeMac-mini:snapkite-engine alyssa$ npm start

> snapkite-engine@0.1.2 start /Users/alyssa/snapkite-engine
> node app.js

/Users/alyssa/snapkite-engine/node_modules/node-tweet-stream/lib/twitter.js:28
    throw new Error('Oauth credentials required')
    ^

Error: Oauth credentials required
    at new Twitter (/Users/alyssa/snapkite-engine/node_modules/node-tweet-stream/lib/twitter.js:28:11)
    at module.exports (/Users/alyssa/snapkite-engine/controllers/twitter.js:85:17)
    at Object.<anonymous> (/Users/alyssa/snapkite-engine/app.js:11:33)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snapkite-engine@0.1.2 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the snapkite-engine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs snapkite-engine
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls snapkite-engine
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alyssa/snapkite-engine/npm-debug.log

**Comment by ryentzer** [comment]
I'd guess that you did not enter the necessary token access string in the config file of snapkite-engine per this error: _Error: Oauth credentials required_. I would start there and make sure you added it. If you did then check for typos or an extra space.

**Comment by fedosejev** [comment]
Here's the documentation: https://github.com/Snapkite/snapkite-engine#install
