### ISSUE TITLE
Getting error in first chapter when running npm start

### ISSUE THREAD

**Issue by arvindcg** [fedosejev/react-essentials#9]
here is the npm log----
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'owner',
1 verbose cli   'ls',
1 verbose cli   'snapkite-engine' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose node symlink /usr/bin/node
5 silly mapToRegistry name snapkite-engine
6 silly mapToRegistry using default registry
7 silly mapToRegistry registry https://registry.npmjs.org/
8 silly mapToRegistry uri https://registry.npmjs.org/snapkite-engine
9 verbose request uri https://registry.npmjs.org/snapkite-engine
10 verbose request no auth needed
11 info attempt registry request try #1 at 14:23:17
12 verbose request id dcd250294389cade
13 http request GET https://registry.npmjs.org/snapkite-engine
14 http 404 https://registry.npmjs.org/snapkite-engine
15 verbose headers { 'content-type': 'application/json',
15 verbose headers   'cache-control': 'max-age=0',
15 verbose headers   'content-length': '2',
15 verbose headers   'accept-ranges': 'bytes',
15 verbose headers   date: 'Wed, 23 Sep 2015 08:53:19 GMT',
15 verbose headers   via: '1.1 varnish',
15 verbose headers   age: '0',
15 verbose headers   connection: 'keep-alive',
15 verbose headers   'x-served-by': 'cache-sin6921-SIN',
15 verbose headers   'x-cache': 'MISS',
15 verbose headers   'x-cache-hits': '0',
15 verbose headers   'x-timer': 'S1442998398.298257,VS0,VE858' }
16 silly get cb [ 404,
16 silly get   { 'content-type': 'application/json',
16 silly get     'cache-control': 'max-age=0',
16 silly get     'content-length': '2',
16 silly get     'accept-ranges': 'bytes',
16 silly get     date: 'Wed, 23 Sep 2015 08:53:19 GMT',
16 silly get     via: '1.1 varnish',
16 silly get     age: '0',
16 silly get     connection: 'keep-alive',
16 silly get     'x-served-by': 'cache-sin6921-SIN',
16 silly get     'x-cache': 'MISS',
16 silly get     'x-cache-hits': '0',
16 silly get     'x-timer': 'S1442998398.298257,VS0,VE858' } ]
17 error owner ls Couldn't get owner data snapkite-engine
18 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/snapkite-engine
18 verbose stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:239:14)
18 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
18 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:354:22)
18 verbose stack     at Request.emit (events.js:110:17)
18 verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1207:14)
18 verbose stack     at Request.emit (events.js:129:20)
18 verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1153:12)
18 verbose stack     at IncomingMessage.emit (events.js:129:20)
18 verbose stack     at _stream_readable.js:908:16
18 verbose stack     at process._tickCallback (node.js:355:11)
19 verbose statusCode 404
20 verbose pkgid snapkite-engine
21 verbose cwd /home/bern/snapkite-engine
22 error Linux 3.19.0-29-generic
23 error argv "/usr/bin/node" "/usr/bin/npm" "owner" "ls" "snapkite-engine"
24 error node v0.12.7
25 error npm  v2.11.3
26 error code E404
27 error 404 Registry returned 404 for GET on https://registry.npmjs.org/snapkite-engine
27 error 404
27 error 404 'snapkite-engine' is not in the npm registry.
27 error 404 You should bug the author to publish it (or use the name yourself!)
27 error 404
27 error 404 Note that you can also install from a
27 error 404 tarball, folder, http url, or git url.
28 verbose exit [ 1, true ]

**Comment by gcardella** [comment]
Install v0.10.40 of Node.js - this version, at time of writing, is a version that supports Jest.

**Comment by fedosejev** [comment]
Error: `27 error 404 'snapkite-engine' is not in the npm registry.`

@arvindcg, have you cloned https://github.com/Snapkite/snapkite-engine?

**Comment by fedosejev** [comment]
I'll consider this resolved.
