### ISSUE TITLE
Chapter 1 Error with npm start

### ISSUE THREAD

**Issue by Moyowalker** [fedosejev/react-essentials#93]
> `> snapkite-engine@0.1.2 start /Users/mac/Desktop/snapkite-engine
> node app.js

[Snapkite][Socket] Listening on port 3000
module.js:457
    throw err;
    ^

Error: Cannot find module '../filters/snapkite-filter-is-possibly-sensitive'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /Users/mac/Desktop/snapkite-engine/controllers/twitter.js:67:20
    at Array.forEach (native)
    at isValidTweet (/Users/mac/Desktop/snapkite-engine/controllers/twitter.js:65:30)
    at Twitter.<anonymous> (/Users/mac/Desktop/snapkite-engine/controllers/twitter.js:93:9)
    at emitOne (events.js:96:13)
    at Twitter.emit (events.js:188:7)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snapkite-engine@0.1.2 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the snapkite-engine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs snapkite-engine
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls snapkite-engine
npm ERR! There is likely additional logging output above.
![screen shot 2016-09-13 at 3 21 18 pm](https://cloud.githubusercontent.com/assets/15801018/18477519/d396af64-79c5-11e6-8cf1-187832fe9d3f.png)

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mac/Desktop/snapkite-engine/npm-debug.log`

**Comment by fedosejev** [comment]
@skywalkerKFG you probably have missed the step in the book where you need to install `snapkite-filter-is-possibly-sensitive` filter:
`git clone https://github.com/snapkite/snapkite-filter-is-possibly-sensitive.git`
