### ISSUE TITLE
there are some errors when I run "npm start" in chapter 1

### ISSUE THREAD

**Issue by OliveKong** [fedosejev/react-essentials#94]
![image](https://cloud.githubusercontent.com/assets/7875818/19720741/fa578b16-9ba1-11e6-81b8-0d1426ff3d69.png)
I do not know what is the meaning of those errors,need some help,thanks

**Comment by fedosejev** [comment]
@OliveKong the problem is in your `config.json` file. Please check it has no weird characters, etc. It should be a valid JSON format.

**Comment by OliveKong** [comment]
Thanks！I had solved this problem. @fedosejev
